name: Deploiement auto Serveur

on: 
  push:
    branches: main

jobs: 
  deploy:
    runs-on: debian-latest
    steps:
    - name: Install dependencies
      run: npm install
      
    - name: Build the project
      run: npm run build
    - name: pull
      run: git pull origin main
