name: Deploiement auto Serveur

on: 
  push:
    branches: main

jobs: 
  deploy:
    runs-on: debian-latest
    steps:
    - name: cd
      run: cd /var/www/reeper.buzz/html/ProjetCloud
    - name: pull
      run: git pull origin
